### PR TITLE
Can I join

### PR DESCRIPTION
**Pull request by bahabryra**
Can I join if so email Riyad.bahabry@gmail.com and riyadbahabry@yahoo.com in the same email or DM me on discord @bahabryra

### CODE REVIEW

**Comment by 22yeets22** [comment]
You can PR

**Comment by bahabryra** [comment]
I want to be part of the team with RednotSus and you






On Tuesday, April 16, 2024 at 05:22:28 PM CDT, 22yeets22 ***@***.***> wrote: 







You can PR

**Comment by RedNotSus** [comment]
22yeets22 had to make like 10 prs before I let him have push access

**Comment by RedNotSus** [comment]
once you get like 10 merged prs I might think of it so untill then no

**Pull request closed without merging**
