### PR TITLE
Changed the background

### PR DESCRIPTION
**Pull request by CiscoBandit1**

### CODE REVIEW

**Comment by 22yeets22** [comment]
Why is this necessary?
Also uh we don't really like JQuery here...
But thanks I guess?

**Comment by RedNotSus** [comment]
real

**Comment by CiscoBandit1** [comment]
My bad 😓

**Comment by 22yeets22** [comment]
> My bad 😓

;-;

**Comment by CiscoBandit1** [comment]
But

**Comment by CiscoBandit1** [comment]
I have this digital clock and I’ll give it to you just because

**Pull request closed without merging**
