### PR TITLE
Discord Used By aptoide :) and also apkonline.net has an android emulator

### PR DESCRIPTION
**Pull request by bahabryra**

### CODE REVIEW

**Comment by bahabryra** [comment]
Please note that I only want to merge aptoide if it merges anything else feel free to remove :)

**Comment by bahabryra** [comment]
@RedNotSus
 @22yeets22

**Comment by bahabryra** [comment]
Please do reply or merge

**Comment by RedNotSus** [comment]
aptiodide doesn't work currently, we are working on migrating to a new server

**Comment by bahabryra** [comment]
can you at least add apkonline

**Comment by RedNotSus** [comment]
you do it

**Comment by RedNotSus** [comment]
make sure to SYNC CHANGES on your fork

**Pull request closed without merging**
