### PR TITLE
Optimizations and backup repository in server code

### PR DESCRIPTION
**Pull request by 22yeets22**
Review carefully @RedNotSus

### CODE REVIEW

**Comment by RedNotSus** [comment]
what's the point of this

**Comment by 22yeets22** [comment]
> what's the point of this

- improve performance
- error handling
- backup repo

**Comment by 22yeets22** [comment]
> > what's the point of this
> 
> * improve performance
> * error handling
> * backup repo
> * and it looks nicer

**Comment by RedNotSus** [comment]
ok

**Comment by 22yeets22** [comment]
> ok

can u test on alt server

**Comment by RedNotSus** [comment]
doing that when I get home

**Pull request closed without merging**
