### PR TITLE
everything fixes

### PR DESCRIPTION
**Pull request by 22yeets22**

### CODE REVIEW

**Comment by RedNotSus** [comment]
https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/

**Comment by RedNotSus** [comment]
WHAT DID YOU CHANGE

**Comment by 22yeets22** [comment]
uh i was in a hurry i forgot

**Comment by 22yeets22** [comment]
oh yeah there is a loading thing in the games now :)

**Comment by 22yeets22** [comment]
review and merge @RedNotSus

**Pull request merged**
