### PR TITLE
Optimize 1

### PR DESCRIPTION
**Pull request by 22yeets22**
SPEEEEEEEED
Test it @RedNotSus

### CODE REVIEW

**Comment by RedNotSus** [comment]
I will test this soon

**Comment by 22yeets22** [comment]
thx if doesn't work tell me

**Comment by RedNotSus** [comment]
images doesnt load with games - looks like its not reaching the server correctly

**Comment by 22yeets22** [comment]
talk on discord

**Review by RedNotSus — CHANGES_REQUESTED** [review]
yay

**Pull request merged**
